### ISSUE TITLE
No hits were sent by this tag

### ISSUE THREAD

**Issue by robsonsobral** [johannschopplich/nuxt-gtag#74] opened 2024-06-12 18:14 UTC
### Environment

- Operating System: Windows_NT
- Node Version:     v20.14.0
- Nuxt Version:     3.11.2
- CLI Version:      3.11.1
- Nitro Version:    2.9.6
- Package Manager:  npm@9.6.3
- Builder:          -
- User Config:      app, build, css, devtools, i18n, modules, runtimeConfig, vite, typescript
- Runtime Modules:  @nuxtjs/i18n@8.3.1, @pinia/nuxt@0.5.1, @nuxtjs/mdc@0.2.9, @pinia-plugin-persistedstate/nuxt@1.2.0, nuxt-gtag@2.0.5
- Build Modules:    -

### Reproduction

Load a gTag using an ENV variable and a second one using `initialize()`.

```js
const { initialize } = useGtag();

  if (!import.meta.dev && import.meta.client) {
    if (campaign.value.google_analytics) {
      initialize(campaign.value.google_analytics);
    }
  }
```

### Describe the bug

The second tag ID hasn't its events track.

![image](https://github.com/johannschopplich/nuxt-gtag/assets/931642/adad0ad9-b7ff-4d2a-b73c-a87aecd984e1)

**Comment by johannschopplich** [comment] 2024-06-13 05:21
Hi there, sorry, but I can't reproduce this with the latest verion of Nuxt Gtag. Can you please upgrade to the latest version [v2.0.6](https://github.com/johannschopplich/nuxt-gtag/releases/tag/v2.0.6)?

**Comment by johannschopplich** [comment] 2024-06-18 16:06
I haven't tried the behavior with Google IDs from different accounts. Maybe they require some other handling, I'm not sure… Reproduction much appreciated!

**Comment by johannschopplich** [comment] 2024-08-26 10:59
Closing this, as no reproduction was provided. If the problem persists, please open a new issue with a reproduction attached. Thanks! 🙏

**Closed by johannschopplich** 2024-08-26 10:59 UTC
