### ISSUE TITLE
Analytics Hits Not Registered After Update to 1.2.0

### ISSUE THREAD

**Issue by tberk** [johannschopplich/nuxt-gtag#47] opened 2024-02-22 12:17 UTC
### Environment

- Operating System: Windows_NT
- Node Version:     v18.17.1
- Nuxt Version:     3.10.2
- CLI Version:      3.10.1
- Nitro Version:    2.8.1
- Package Manager:  pnpm@8.15.3
- Builder:          -
- User Config:      modules, runtimeConfig, routeRules, app, vite, build, radix, gtag, colorMode, auth, typescript, devtools
- Runtime Modules:  @sidebase/nuxt-auth@0.6.7, @vueuse/nuxt@10.8.0, @nuxtjs/device@3.1.1, @pinia/nuxt@0.5.1, @pinia-plugin-persistedstate/nuxt@1.2.0, @nuxtjs/tailwindcss@6.11.4, @nuxtjs/color-mode@3.3.2, nuxt-swiper@1.2.2, nuxt-icon@0.6.8, radix-vue/nuxt, shadcn-nuxt@0.9.0, nuxt-gtag@1.1.2
- Build Modules:    -

### Reproduction

I only updated from 1.1.2 to 1.2.0, no configs changed.

``` 
gtag: {
  id: 'G-****',
},
  ```

### Describe the bug

I updated from version 1.1.2 to 1.2.0 and checked for any breaking changes but didn't find any. However, when I reviewed the analytics today, I noticed that hits had not been registered for a week, coinciding with the application of the update. There were random users from Poland across all my projects.

Reverting back to version 1.1.2 resolved the issue.

![analytics](https://github.com/johannschopplich/nuxt-gtag/assets/11773408/15fb47ba-cf75-4db0-ae05-8e34b41b53db)

**Comment by johannschopplich** [comment] 2024-02-22 12:42
Sorry for the inconvenience. I think it's related to the refactors. You're right, there weren't any breaking changes. However, I have changed the default value for `config` from `{}` to `undefined`. But Nuxt defaults to an empty string if no value is provided. Should be fixed in the next version.

Please keep me posted if the issue is resolved. If not, feel free to open another issue. :)

**Closed** 2024-02-22 12:43 UTC
