### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'update')

### ISSUE THREAD

**Issue by MaxCpp** [johannschopplich/nuxt-gtag#56] opened 2024-03-13 01:07 UTC
### Environment

- Operating System: Darwin
- Node Version:     v20.9.0
- Nuxt Version:     3.10.2
- CLI Version:      3.10.1
- Nitro Version:    2.8.1
- Package Manager:  npm@10.1.0
- Builder:          -
- User Config:      devtools, runtimeConfig, ignore, dev, ssr, hooks, components, vite, css, modules, i18n, app
- Runtime Modules:  @pinia/nuxt@0.4.11, @nuxtjs/i18n@8.1.1, nuxt-gtag@2.0.5
- Build Modules:    -

### Reproduction

I try use method initialize with a tag ID in middleware and get in console log error. Example of code with reproduction:
https://stackblitz.com/edit/github-rf1dov?file=middleware%2Fdetect.global.js,nuxt.config.ts

### Describe the bug

I have in console log the error:
![image](https://github.com/johannschopplich/nuxt-gtag/assets/5812783/3f48d4b6-a691-4422-ad57-20bece5b16d1)

### Logs

```shell-script
Uncaught TypeError: Cannot read properties of undefined (reading 'update')
    at config (js?id=G-Z6KBJM98PX:452:69)
    at Oy (js?id=G-Z6KBJM98PX:465:472)
    at Qy (js?id=G-Z6KBJM98PX:467:43)
```

**Comment by johannschopplich** [comment] 2024-03-13 08:21
@MaxCpp Unfortunately, your reproduction doesn't produce an error. It seems to work just fine:

![grafik](https://github.com/johannschopplich/nuxt-gtag/assets/27850750/fb7d9924-b218-4c7a-a850-af0c5d334410)

Can you please update the reproduction?

**Comment by MaxCpp** [comment] 2024-03-13 09:40
> @MaxCpp Unfortunately, your reproduction doesn't produce an error. It seems to work just fine:
> 
> ![grafik](https://private-user-images.githubusercontent.com/27850750/312369239-fb7d9924-b218-4c7a-a850-af0c5d334410.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzMjMwNzMsIm5iZiI6MTcxMDMyMjc3MywicGF0aCI6Ii8yNzg1MDc1MC8zMTIzNjkyMzktZmI3ZDk5MjQtYjIxOC00YzdhLWE4NTAtYWYwYzVkMzM0NDEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDA5MzkzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhMzBmNTNhYTRmZjAxOGM0MGU3MzJiOTk2ODFhY2RhMDZlMTA2OTYyZGY1YmIwMmU2MzdjZDM5ZDk0OTQ5NDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TbZhKwKzwgzEU1gNLp9aw29aBrhvt5TWsAy83CUyTsM)
> 
> Can you please update the reproduction?

Please open console.

**Comment by johannschopplich** [comment] 2024-03-13 11:15
Thanks for the reproduction! I've opened the web container in a new tab, but there is still no error in the console, unfortunately.

Also, there is no `update` method on any of this module's internals. Any chance you can create another reproduction or share a screen recording?

**Comment by MaxCpp** [comment] 2024-03-13 12:46
Please look:
https://github.com/johannschopplich/nuxt-gtag/assets/5812783/3ed83ae9-793c-4c63-822c-d249e4b3429c

For information. If I add gtag in nuxt.config.js and after uses method `initialize()` I don’t have problem, but if use `initialize(’tag id’)` I have.
Plus I tried add `initialize(’tag id’)` in page or layout, problem the same ((.

**Comment by jessielaf** [comment] 2024-03-13 13:28
I am running into the same problem for the last couple of days. I will try to reproduce the problem. I am finding the same behavior as @MaxCpp where initialize is working with when supplying a tag-id it is not.

**Comment by johannschopplich** [comment] 2024-03-13 14:29
Thank you both! I'm having trouble localizing the issue. 

Does the bug only occur in global middlewares? Can you try to use client-only middlewares? Since the Google Tag won't be initialized on the server anyway, this might simplify the project.

**Comment by jessielaf** [comment] 2024-03-13 16:07
@johannschopplich I was not using global middlewares. When I used `initialize` once the user clicked on the cookie, I also got the same error.

**Comment by MaxCpp** [comment] 2024-03-13 19:09
@johannschopplich client-only middlewares worked for me. Thank you!

**Comment by igor322** [comment] 2024-03-27 23:30
I'm having the same problem, I tried to do in a component onMounted and in a client side plugin, both throws the error:
TypeError: Cannot read properties of undefined (reading 'update')

**Comment by gertjanjansen** [comment] 2024-05-07 19:29
I'm running into the same issue, since a few days. The strange thing is that it started happening 4 days ago while I didn't change anything related to this. I was still using version `1.2.1` but upgrading to `2.0.5` didn't fix it. My setup is similar as described above:

In nuxt.config.ts I have:
```
gtag: {
    id: undefined,
    enabled: false,
  },
```

Then I have a **client only** component, where I do this:

```
const { initialize } = useGtag()
initialize(myGoogleTagId)
```
I tried a few things like putting it in an onMounted hook, but nothing helped.

However, as soon as I set the `id` in nuxt.config.ts, it works fine. It looks like setting the id to `G-0000000000` also works, though I need to investigate a bit more.

**Comment by marcbejar** [comment] 2024-05-16 21:46
I'm facing the same issue. In my case I have a function `const acceptTracking = () => { initialize('G-XXXXXXXXXX') }` that triggers when a user have the cookies accepted or just accepted the cookies. The code runs in a layout in the `<script setup lang="ts">` tag.

**Comment by johannschopplich** [comment] 2024-05-17 06:19
I think I have found the issue. Gtag always requires a default config value to be set, which wasn't the case if you used the `initialize('<id>')` multi-tenancy support. Fixed in https://github.com/johannschopplich/nuxt-gtag/commit/3d9ea7d7715fdcc056e584c01154113581d07cf3.

Please try [v2.0.6](https://github.com/johannschopplich/nuxt-gtag/releases/tag/v2.0.6). Thanks!

**Comment by marcbejar** [comment] 2024-05-17 09:00
> I think I have found the issue. Gtag always requires a default config value to be set, which wasn't the case if you used the `initialize('<id>')` multi-tenancy support. Fixed in [3d9ea7d](https://github.com/johannschopplich/nuxt-gtag/commit/3d9ea7d7715fdcc056e584c01154113581d07cf3).
> 
> Please try [v2.0.6](https://github.com/johannschopplich/nuxt-gtag/releases/tag/v2.0.6). Thanks!

That works for for my case!

**Comment by johannschopplich** [comment] 2024-05-17 10:22
@MaxCpp @jessielaf @gertjanjansen Please upgrade to [v2.0.6](https://github.com/johannschopplich/nuxt-gtag/releases/tag/v2.0.6). I have fixed the bug. You remove the empty Nuxt config Gtag `id` workaround and use `initialize` as intended now. Thanks for your patience! 🎬

**Closed by johannschopplich** 2024-05-17 10:22 UTC
Labels: needs reproduction

**Comment by gertjanjansen** [comment] 2024-05-28 13:04
@johannschopplich I investigated a bit more. This might need it's own issue, but I think I already have the solution so I'll post it here:

On this line, the `initCommands` are taken into account: https://github.com/johannschopplich/nuxt-gtag/blob/108a7d3485787d6ad539929bed4d9cbc44485f80/src/runtime/utils.ts#L13
But on this line they aren't: https://github.com/johannschopplich/nuxt-gtag/blob/108a7d3485787d6ad539929bed4d9cbc44485f80/src/runtime/composables/useGtag.ts#L26

Therefore, with multi-tenancy the initCommands don't work.

The simplest - but not cleanest - solution is to replace line 26 in `useGtag` with this:
```
const _options = toRaw(options);
const { config, initCommands } = _options;
tag = { id: id, config, initCommands }
```

**Comment by johannschopplich** [comment] 2024-05-28 18:56
@gertjanjansen Please open a separate issue. Thanks!
