### ISSUE TITLE
2.0.7 breaks module import

### ISSUE THREAD

**Issue by jblyberg** [johannschopplich/nuxt-gtag#84] opened 2024-07-18 15:59 UTC
### Environment

```
- Operating System: Darwin
- Node Version:     v22.4.0
- Nuxt Version:     3.12.3
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  pnpm@9.2.0
- Builder:          -
- User Config:      compatibilityDate, extends, modules, app, build, colorMode, css, devServer, devtools, future, gtag, hooks, postcss, runtimeConfig, site, ui, uiPro
- Runtime Modules:  @nuxt/content@2.13.1, @nuxt/image@1.7.0, @nuxt/ui@2.17.0, @nuxtjs/sitemap@5.3.5, nuxt-gtag@2.0.7, nuxt-og-image@3.0.0-rc.64
- Build Modules:    -
```

### Reproduction

Nuxt 3.12.3 with gtag 2.0.7

### Describe the bug

After upgrading to 2.0.7, gtag fails to load with:

`Loading failed for the module with source “http://localhost:3003/_nuxt/@fs/Users/jblyberg/..../node_modules/.pnpm/nuxt-gtag@2.0.7_magicast@0.3.4_rollup@4.18.1/node_modules/nuxt-gtag/dist/runtime/utils.js?v=4a90b65e”.`

### Additional context

Downgrading to 2.0.6 fixes the issue.

**Comment by johannschopplich** [comment] 2024-07-19 05:57
Thanks for the report. I can't reproduce your error. Can you please provide a reproducible example? Please use a template below to create a minimal reproduction:
👉 https://stackblitz.com/github/nuxt/starter/tree/v3-stackblitz
👉 https://codesandbox.io/p/github/nuxt/starter/v3-codesandbox

Thanks in advance!

**Comment by jblyberg** [comment] 2024-07-19 17:47
OK, so I've been trying to reproduce it but I cannot. But I did discover that the issue only arises when using Firefox

**Comment by johannschopplich** [comment] 2024-07-19 20:41
Thanks for debugging this! Seems like the extension is blocking a specific path, maybe because of the Vite hash? 

Anyway, this seems to be fixed. Closing the issue.

**Closed by johannschopplich** 2024-07-19 20:41 UTC
Labels: bug, needs reproduction

**Comment by ptdev** [comment] 2024-07-23 21:26
Hey, sorry for adding to a closed ticket, but was also hit by this issue and it's really annoying.

Adblock plugins that use the easyprivacy list will have a very generic "/gtag.js" filter that will apparently prevent loading of the initGtag function. (I'm also using ublock origin but many others will probably source the same list)

![image](https://github.com/user-attachments/assets/ffbfdf7a-8078-4e31-8750-4e295ae2ea4b)


The bigger issue is that when this happens, the rest of the app breaks in many unexpected ways as soon as that block happens.

It would be useful to somehow detect if the script/function got loaded or not and disable it gracefully instead of nearly silently breaking the app.

I understand that it's a completely external issue that is causing it, but adblock plugins are so prevalent in the development community, that I'm sure this issue is bound to crop up every once in a while, so some safeguards could be nice.

Just a suggestion, cheers!
